<?php

namespace App\Mail;

use App\Models\JobPost;
use Illuminate\Bus\Queueable;
use Illuminate\Mail\Mailable;
use Illuminate\Queue\SerializesModels;

class JobApprovedMail extends Mailable
{
    use Queueable, SerializesModels;

    public JobPost $job;

    /**
     * Create a new message instance.
     */
    public function __construct(JobPost $job)
    {
        $this->job = $job->load([
            'user',
            'category',
        ]);
    }

    /**
     * Build the email.
     */
    public function build()
    {
        $html = '

<!DOCTYPE html>

<html lang="en">

<head>

<meta charset="UTF-8">

<title>Job Approved</title>

</head>

<body style="margin:0;padding:40px;background:#f4f7fb;font-family:Arial,sans-serif;">

<table
width="100%"
cellpadding="0"
cellspacing="0"
>

<tr>

<td align="center">

<table
width="700"
cellpadding="0"
cellspacing="0"
style="background:#fff;border-radius:12px;overflow:hidden;"
>

<tr>

<td
style="background:#16a34a;color:white;padding:35px;text-align:center;"
>

<h1>

Congratulations 🎉

</h1>

<p>

Your job has been approved.

</p>

</td>

</tr>

<tr>

<td style="padding:35px;">

<p>

Hello <strong>'.$this->job->user->name.'</strong>,

</p>

<p>

Your job posting has been reviewed and approved by our administrators.

It is now visible to job seekers.

</p>

<table
width="100%"
cellpadding="12"
style="border-collapse:collapse;margin-top:25px;"
>

<tr style="background:#f8fafc;">

<td><strong>Job Title</strong></td>

<td>'.$this->job->title.'</td>

</tr>

<tr>

<td><strong>Category</strong></td>

<td>'.$this->job->category->name.'</td>

</tr>

<tr style="background:#f8fafc;">

<td><strong>Location</strong></td>

<td>'.$this->job->location.'</td>

</tr>

<tr>

<td><strong>Job Type</strong></td>

<td>'.ucfirst($this->job->job_type).'</td>

</tr>

<tr style="background:#f8fafc;">

<td><strong>Salary</strong></td>

<td>'.$this->job->currency.' '.number_format($this->job->payment,2).'</td>

</tr>

<tr>

<td><strong>Employees Needed</strong></td>

<td>'.$this->job->employee_needed.'</td>

</tr>

<tr style="background:#f8fafc;">

<td><strong>Expire Date</strong></td>

<td>'.$this->job->expire_date.'</td>

</tr>

</table>

<h3 style="margin-top:35px;">

Job Description

</h3>

<p>

'.nl2br(e($this->job->description)).'

</p>

<h3>

About Company

</h3>

<p>

'.nl2br(e($this->job->about_us)).'

</p>

<h3>

Responsibilities

</h3>

<p>

'.nl2br(e($this->job->what_you_do)).'

</p>

<div
style="margin-top:40px;text-align:center;"
>

<a
href="http://localhost:3000//jobs/'.$this->job->id.'"
style="
background:#16a34a;
color:white;
padding:15px 35px;
text-decoration:none;
border-radius:8px;
display:inline-block;
font-size:16px;
"
>

View Job

</a>

</div>

<hr style="margin-top:40px;">

<p
style="
color:#777;
font-size:13px;
text-align:center;
"
>

This email was automatically generated by the Knowledge Path Platform.

</p>

</td>

</tr>

</table>

</td>

</tr>

</table>

</body>

</html>

        ';

        return $this
            ->subject('🎉 Your Job Post Has Been Approved')
            ->html($html);
    }
}