<?php

namespace App\Mail;

use App\Models\JobPost;
use Carbon\Carbon;
use Illuminate\Bus\Queueable;
use Illuminate\Mail\Mailable;
use Illuminate\Queue\SerializesModels;

class JobPostPendingApprovalMail extends Mailable
{
    use Queueable, SerializesModels;

    public JobPost $job;

    public function __construct(JobPost $job)
    {
        $this->job = $job;
    }

    public function build()
    {
        $job = $this->job;

        return $this
            ->subject('📝 New Job Post Awaiting Approval')
            ->html('

<!DOCTYPE html>

<html>

<head>

<meta charset="UTF-8">

<title>New Job Pending Approval</title>

</head>

<body style="margin:0;padding:40px;background:#f4f7fb;font-family:Arial,Helvetica,sans-serif;">

<table width="100%" cellpadding="0" cellspacing="0">

<tr>

<td align="center">

<table width="700" cellpadding="0" cellspacing="0" style="background:#fff;border-radius:12px;overflow:hidden;">

<tr>

<td style="background:#2563eb;padding:30px;text-align:center;color:#fff;">

<h1 style="margin:0;">New Job Post Submitted</h1>

<p style="margin-top:10px;">
Waiting for Administrator Approval
</p>

</td>

</tr>

<tr>

<td style="padding:35px;">

<p>Hello Administrator,</p>

<p>
A new job has been submitted and is waiting for your approval.
</p>

<table width="100%" cellpadding="10" cellspacing="0" style="border-collapse:collapse;">

<tr>
<td><strong>Title</strong></td>
<td>'.$job->title.'</td>
</tr>

<tr style="background:#f8fafc;">
<td><strong>Category</strong></td>
<td>'.$job->category->name.'</td>
</tr>

<tr>
<td><strong>Posted By</strong></td>
<td>'.$job->user->name.'</td>
</tr>

<tr style="background:#f8fafc;">
<td><strong>Email</strong></td>
<td>'.$job->user->email.'</td>
</tr>

<tr>
<td><strong>Location</strong></td>
<td>'.$job->location.'</td>
</tr>

<tr style="background:#f8fafc;">
<td><strong>Job Type</strong></td>
<td>'.ucfirst($job->job_type).'</td>
</tr>

<tr>
<td><strong>Salary</strong></td>
<td>'.$job->currency.' '.number_format($job->payment,2).'</td>
</tr>

<tr style="background:#f8fafc;">
<td><strong>Employees Needed</strong></td>
<td>'.$job->employee_needed.'</td>
</tr>

<tr>
<td><strong>Additional Compensation</strong></td>
<td>'.($job->additional_compensation ?: 'None').'</td>
</tr>

<tr style="background:#f8fafc;">
<td><strong>Qualification Required</strong></td>
<td>'.($job->enable_qualification ? 'Yes' : 'No').'</td>
</tr>

'.(
$job->enable_qualification
?

'<tr>

<td><strong>Qualification</strong></td>

<td>'.$job->qualification.'</td>

</tr>'

: ''

).'

<tr style="background:#f8fafc;">

<td><strong>Experience Required</strong></td>

<td>'.($job->enable_experience ? 'Yes' : 'No').'</td>

</tr>

'.(

$job->enable_experience

?

'<tr>

<td><strong>Experience</strong></td>

<td>'.$job->experience.'</td>

</tr>'

: ''

).'

'.(

$job->enable_year_experience

?

'<tr>

<td><strong>Years of Experience</strong></td>

<td>'.$job->year_experience.' Years</td>

</tr>'

: ''

).'

<tr style="background:#f8fafc;">

<td><strong>Payment Required</strong></td>

<td>'.($job->payment_required ? 'Yes' : 'No').'</td>

</tr>

<tr>

<td><strong>Expire Date</strong></td>

<td>'.Carbon::parse($job->expire_date)->format('d M Y').'</td>

</tr>

<tr style="background:#f8fafc;">

<td><strong>Status</strong></td>

<td>

<span style="background:#fbbf24;padding:6px 14px;border-radius:20px;font-weight:bold;">

Pending Approval

</span>

</td>

</tr>

</table>

<h3 style="margin-top:35px;">

Job Description

</h3>

<p>'.nl2br(e($job->description)).'</p>

<h3>

About Company

</h3>

<p>'.nl2br(e($job->about_us)).'</p>

<h3>

Responsibilities

</h3>

<p>'.nl2br(e($job->what_you_do)).'</p>

<div style="text-align:center;margin-top:40px;">

<a

href="http://localhost:3000//admin/jobs"

style="background:#2563eb;color:#fff;padding:15px 35px;text-decoration:none;border-radius:8px;">

Review Job Request

</a>

</div>

<hr style="margin-top:40px;">

<p style="font-size:13px;color:#777;text-align:center;">

This email was automatically generated by the Knowledge Path Platform.

</p>

</td>

</tr>

</table>

</td>

</tr>

</table>

</body>

</html>

');
    }
}